### ISSUE TITLE
Time for an update?

### ISSUE THREAD

**Issue by Klortho** [XSLTdoc/XSLTdoc#1]
I created a new copy of this project at https://github.com/Klortho/XSLTdoc. I imported all the commit history from subversion. I started it out as a fork of this one, but then abandoned that idea -- it was hard to figure out how to graft your commits onto the HEAD of the subversion history, so I just did a merge and cherry-picks instead. So, the heads of mine and yours are identical, and your commits still show up.

Since you have this "XSLTdoc" account, how would you feel about replacing this one with mine, and making me a committer?

**Comment by davrek** [comment]
Sure, go ahead. I converted the account into an organization and invited you. See, if you can set it up the way you intended. If it all works out, I'd be glad to pass this over to you.

**Comment by Klortho** [comment]
Thanks! I finally managed to get the commit history cleaned up, and did some polishing work on the documentation. I haven't heard back from the original authors, but maybe its because its the weekend.
